sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-8.0.2

language: c

before_install:
  - export PATH=/opt/ghc/8.0.2/bin:/opt/cabal/1.24/bin:$PATH

before_script:
  - python -m SimpleHTTPServer 8000 &

script:
  - cabal update
  - cabal sandbox init
  - cabal install
  - make

after_script:
  - pkill python
