sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.3

language: c

script:
  - cabal update
  - cabal configure
  - cabal install
  - make

before_script:
  - python -m SimpleHTTPServer 8000 &

before_install:
  - export PATH=/opt/ghc/7.10.3/bin:/opt/cabal/1.22/bin:$PATH
